on:
    push:
      branches:
        - main

name: 🚀 Deploy website on push to main

jobs:
    job1:
        name: 🎉 SSH connect and clear cache
        runs-on: ubuntu-latest
        steps:
        - name: PHP artisan using ssh
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.LIVE_SSH_HOST }}
            username: ${{ secrets.LIVE_SSH_USERNAME }}
            password: ${{ secrets.LIVE_SSH_PASSWORD }}
            script: |
              cd /home/elha-enterprises/htdocs/www.elha-enterprises.com
              git pull origin main
              cp .env.live .env
              composer install
              php artisan route:cache
              php artisan view:clear
              php artisan cache:clear
              
